from prometheus_client import Counter
from prometheus_client import Gauge
from prometheus_client import Histogram

HTTP_REQUESTS_TOTAL = Counter(
    "signal_engine_http_requests_total",
    "Total HTTP requests handled by the Signal Engine.",
    ["method", "path", "status_code"]
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "signal_engine_http_request_duration_seconds",
    "HTTP request duration in seconds.",
    ["method", "path"]
)

ZERO_RESULT_QUERIES_TOTAL = Counter(
    "signal_engine_zero_result_queries_total",
    "Total search queries that returned zero results."
)

SIGNALS_TOTAL = Counter(
    "signal_engine_signals_total",
    "Total signals generated by the detectors.",
    ["signal_type", "severity"]
)

ACTIVE_SIGNALS = Gauge(
    "signal_engine_active_signals",
    "Current number of recent signals retained in memory."
)
